client_id = "1834e252e45d75072a226db1f3ce1f20"
name = "Simpli Sections"
application_url = "https://simpli-sections-production.up.railway.app"
embedded = true
handle = "simpli-sections"

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes"
use_legacy_install_flow = true

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = [
  "https://simpli-sections-production.up.railway.app/auth/callback",
  "https://simpli-sections-production.up.railway.app/auth/shopify/callback",
  "https://simpli-sections-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = true